version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwd
      ME_CONFIG_MONGODB_URL: mongodb://root:passwd@mongo:27017/

  node:
    depends_on:
      - mongo
    image: yamatairiku0dev/mongo-app
    container_name: mongo-app
    restart: always
    ports: 
      - 8080:3000
    environment: 
      NODE_CONFIG_MONGODB_URL: mongodb://root:passwd@mongo:27017/recipe_db?authSource=admin
    tty: true
